#!/usr/bin/env bash
# Installs and configures HAproxy load balancer

sudo echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | sudo  tee /etc/apt/sources.list.d/backports.list
sudo apt-get update
sudo apt-get install haproxy -t trusty-backports
sudo service haproxy start
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo $'backend servers\n\tbalance roundrobin\n\tserver 354-web-01 35.237.60.90\n\tserver 354-web-02 35.237.27.137' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy reload
sudo service haproxy restart
