#!/usr/bin/env bash
# Configures nginx server to listen on port 80

FILE=/etc/nginx/sites-enabled/default
REPLACE="80"

sudo sed -i "21s/8080/$REPLACE/" $FILE
sudo sed -i "22s/8080/$REPLACE/" $FILE

sudo service nginx restart
