#!/usr/bin/env bash
# manages manage_my_process
. /lib/lsb/init-functions

start()
{
./manage_my_process &
echo "$!" | tee /var/run/my_process.pid > /dev/null
}

stop()
{
kill "$(cat /var/run/my_process.pid)"
rm /var/run/my_process.pid
}

restart()
{
stop
start
}

case "$1" in
start)
	start
	echo "manage_my_process started"
;;
stop)
	stop
	echo "manage_my_process stopped"
;;
restart)
	restart
	echo "manage_my_process restarted"
;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
esac
