#!/usr/bin/env bash
# This script counts to 20, printing unlucky numers
COUNTER=1
while [ $COUNTER -le 20 ]
do
	echo $COUNTER
	case $COUNTER in
		4 )
			echo "bad luck from China";;
		9 )
			echo "bad luck from Japan";;
		17 )
			echo "bad luck from Italy";;
	esac
	let COUNTER=COUNTER+1
done
