#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
MINUTES=1
HOURS=0
while [ $HOURS -lt 13 ]
do
MINUTES=1
echo "Hour: $HOURS"
	while [ $MINUTES -lt 60 ]
	do
		echo $MINUTES
		let MINUTES+=1
	done
	let HOURS+=1
done
