#!/usr/bin/env bash
# This script checks a holbertonschool file
MYFILE="holbertonschool"
if [ -e $MYFILE ]
then
	echo "holbertonschool file exists"
	if [ -s $MYFILE ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $MYFILE ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi

