#!/usr/bin/env bash
# Installs and configures nginx server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School" | sudo tee usr/share/nginx/html/index.html
