#!/usr/bin/env bash
# Installs and configures nginx server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | usr/share/nginx/index.html
