#!/usr/bin/env bash
# Configures nginx so /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "26i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent" /etc/nginx/sites-enabled/default
sudo service nginx restart
