#!/usr/bin/env bash
# Configures nginx so /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\treturn 301;\n\t}\n"  /etc/nginx/sites_available/default
sudo service nginx restart
