#!/usr/bin/env bash
# Configures nginx so /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "39i\ \tlocation /redirect_me {\n\t\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
