#!/usr/bin/env bash
# configures server to run as nginx user

chmod 777 /etc/nginx/nginx.conf

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/[::]:80 default_server/[::]:8080 default_server/' /etc/nginx/sites-available/default

pkill apache2
sudo service nginx restart
su -u nginx

