#!/usr/bin/env bash
# configures server to run as nginx user

chmod 777 /etc/nginx/nginx.conf

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080' /etc/nginx/sites-available/default
sed -i 's/[::]:80/[::]:8080' /etc/nginx/sites-available/default

pkill apache2
sudo service nginx restart
