#!/usr/bin/env bash
# configures server to run as nginx user

chmod 777 /etc/nginx/nginx.conf

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80 default_server/listen 8080 default/' /etc/nginx/sites-available/default

su nginx -c "service nginx start"
